-- Cash Lojo: migración incremental de STAGING a PRODUCCIÓN
-- Solo estructura. No copia datos de staging.
-- Conserva todas las filas existentes en producción.
-- Generado a partir de los dumps aportados por el usuario.

BEGIN;
CREATE TABLE IF NOT EXISTS "public"."bingo_cards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "promotion_id" "uuid" NOT NULL,
    "edition_id" "uuid" NOT NULL,
    "cliente_id" "uuid" NOT NULL,
    "entitlement_id" "uuid" NOT NULL,
    "card" "jsonb" NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "line_completed" boolean DEFAULT false NOT NULL,
    "bingo_completed" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "won_at" timestamp with time zone,
    CONSTRAINT "bingo_cards_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'won'::"text", 'expired'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."bingo_cartones" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "cliente_id" "uuid" NOT NULL,
    "carton" "jsonb" NOT NULL,
    "numeros_marcados" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "estado" "text" DEFAULT 'activo'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "bingo_cartones_estado_check" CHECK (("estado" = ANY (ARRAY['activo'::"text", 'completado'::"text", 'archivado'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."bingo_draws" (
    "id" bigint NOT NULL,
    "promotion_id" "uuid" NOT NULL,
    "edition_id" "uuid" NOT NULL,
    "number" smallint NOT NULL,
    "drawn_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "bingo_draws_number_check" CHECK ((("number" >= 1) AND ("number" <= 90)))
);

ALTER TABLE "public"."bingo_draws" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."bingo_draws_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."bingo_entitlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "promotion_id" "uuid" NOT NULL,
    "edition_id" "uuid" NOT NULL,
    "cliente_id" "uuid" NOT NULL,
    "order_id" "text" NOT NULL,
    "qualified_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "consumed_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "public"."bingo_games" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "customer_phone" "text" NOT NULL,
    "created_from_participation_id" "uuid",
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "card" "jsonb" NOT NULL,
    "remaining_numbers" "jsonb" NOT NULL,
    "drawn_numbers" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "line_completed" boolean DEFAULT false NOT NULL,
    "bingo_completed" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "completed_at" timestamp with time zone,
    CONSTRAINT "bingo_games_status_valid" CHECK (("status" = ANY (ARRAY['active'::"text", 'completed'::"text", 'cancelled'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."clientes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nombre" "text" NOT NULL,
    "telefono" "text" NOT NULL,
    "activo" boolean DEFAULT true NOT NULL,
    "token" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "enlace_personal" "text",
    "estado" "text" DEFAULT 'activo'::"text"
);

CREATE TABLE IF NOT EXISTS "public"."clientes_favoritos" (
    "id" bigint NOT NULL,
    "cliente_id" "uuid" NOT NULL,
    "articulo_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."clientes_favoritos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clientes_favoritos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."game_entitlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "code" "text" NOT NULL,
    "order_id" "text" NOT NULL,
    "customer_token" "text",
    "customer_name" "text",
    "roulette_participation_id" "uuid",
    "roulette_eligible" boolean DEFAULT false NOT NULL,
    "roulette_plays_total" integer DEFAULT 0 NOT NULL,
    "bingo_eligible" boolean DEFAULT false NOT NULL,
    "bingo_reference" "jsonb",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "expires_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "roulette_plays_used" integer DEFAULT 0 NOT NULL,
    "bingo_plays_total" integer DEFAULT 0 NOT NULL,
    "bingo_plays_used" integer DEFAULT 0 NOT NULL,
    "last_bingo_play_at" timestamp with time zone,
    CONSTRAINT "game_entitlements_roulette_plays_total_check" CHECK (("roulette_plays_total" >= 0)),
    CONSTRAINT "game_entitlements_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'completed'::"text", 'cancelled'::"text", 'blocked'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."promociones_bingo" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nombre" "text" DEFAULT 'Promoción bingo principal'::"text" NOT NULL,
    "activa" boolean DEFAULT false NOT NULL,
    "variedad_minima" integer DEFAULT 15 NOT NULL,
    "mensaje_cliente" "text" DEFAULT 'Tu pedido cumple las condiciones para participar en el Bingo.'::"text" NOT NULL,
    "fecha_inicio" "date",
    "fecha_fin" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "premio_linea_activo" boolean DEFAULT true NOT NULL,
    "premio_linea_nombre" "text" DEFAULT ''::"text" NOT NULL,
    "premio_linea_descripcion" "text" DEFAULT ''::"text" NOT NULL,
    "premio_bingo_activo" boolean DEFAULT true NOT NULL,
    "premio_bingo_nombre" "text" DEFAULT ''::"text" NOT NULL,
    "premio_bingo_descripcion" "text" DEFAULT ''::"text" NOT NULL,
    "premio_linea_mensaje" "text" DEFAULT ''::"text" NOT NULL,
    "premio_bingo_mensaje" "text" DEFAULT ''::"text" NOT NULL,
    "premio_linea_articulo_id" "text",
    "premio_bingo_articulo_id" "text",
    "premio_especial_activo" boolean DEFAULT false NOT NULL,
    "premio_especial_nombre" "text" DEFAULT ''::"text" NOT NULL,
    "premio_especial_mensaje" "text" DEFAULT ''::"text" NOT NULL,
    "premio_especial_articulo_id" bigint,
    "premio_especial_max_bolas" integer DEFAULT 50 NOT NULL,
    "edition_id" "uuid" DEFAULT "gen_random_uuid"(),
    CONSTRAINT "promociones_bingo_fechas_validas" CHECK ((("fecha_inicio" IS NULL) OR ("fecha_fin" IS NULL) OR ("fecha_fin" >= "fecha_inicio"))),
    CONSTRAINT "promociones_bingo_premio_bingo_nombre_activo_check" CHECK (((NOT "premio_bingo_activo") OR ("length"("btrim"("premio_bingo_nombre")) > 0))),
    CONSTRAINT "promociones_bingo_premio_especial_activo_check" CHECK (((NOT "premio_especial_activo") OR (("premio_especial_articulo_id" IS NOT NULL) AND ("length"("btrim"("premio_especial_nombre")) > 0)))),
    CONSTRAINT "promociones_bingo_premio_especial_bolas_check" CHECK ((("premio_especial_max_bolas" >= 1) AND ("premio_especial_max_bolas" <= 90))),
    CONSTRAINT "promociones_bingo_premio_linea_nombre_activo_check" CHECK (((NOT "premio_linea_activo") OR ("length"("btrim"("premio_linea_nombre")) > 0))),
    CONSTRAINT "promociones_bingo_variedad_minima_check" CHECK (("variedad_minima" >= 1))
);

CREATE TABLE IF NOT EXISTS "public"."promociones_bingo_articulos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "promocion_id" "uuid" NOT NULL,
    "articulo_id" bigint,
    "codigo_articulo" "text" NOT NULL,
    "nombre_articulo" "text" DEFAULT ''::"text" NOT NULL,
    "cantidad_minima" integer DEFAULT 1 NOT NULL,
    "cuenta_por_venta" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "promociones_bingo_articulos_cantidad_minima_check" CHECK (("cantidad_minima" >= 1))
);

ALTER TABLE "public"."promotion_participations" ADD COLUMN IF NOT EXISTS "bingo_game_id" "uuid";
ALTER TABLE "public"."promotion_participations" ADD COLUMN IF NOT EXISTS "bingo_plays_total" integer DEFAULT 0 NOT NULL;
ALTER TABLE "public"."promotion_participations" ADD COLUMN IF NOT EXISTS "bingo_plays_used" integer DEFAULT 0 NOT NULL;

COMMIT;
